name: core
description: "A IM client"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 5.8.0

# 数据库版本,每次需改数据时,都需要自增一
db_version: 1

environment:
  sdk: ^3.4.0

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  path: ^1.8.3
  shared_preferences: ^2.2.2
  sqflite_common_ffi: ^2.3.2
  sqflite_common_ffi_web: ^0.4.4	
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  web_socket_channel: ^3.0.2
  camera: ^0.10.5+1
  image_picker: ^1.0.7
  geolocator: ^11.0.0
  dio: ^5.8.0+1
  permission_handler: ^11.3.1
  path_provider: ^2.1.1
  device_info_plus: ^11.3.0
  file_picker: ^6.1.2
  flutter_local_notifications: ^18.0.1
  local_notifier: ^0.1.6
  record: ^5.2.0
  logging: ^1.2.0
  package_info_plus: ^8.2.1
  flutter_hooks: ^0.20.5
  hooks_riverpod: ^2.4.0
  riverpod_annotation: ^2.6.1
  flutter_riverpod: ^2.6.1
  xml: ^6.5.0
  get: ^4.7.2
  intl: ^0.20.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  riverpod_generator: ^2.4.0
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10


flutter:
  uses-material-design: true
  assets:
    - assets/
