class ErrorCodes {
  static String getMessage(int code) {
    switch (code) {
      case 0:
        return '正确';
      case 7:
        return '执行一个指令出错';
      case 11:
        return '连接数据库错误';
      case 20:
        return '试用期内，提示用户注册正式版本，剩余天数不足10天，增加属性提示剩余天数';
      case 21:
        return '超出试用期，允许登陆，提示用户注册正式版本';
      case 22:
        return '试用期，超出数据库总人数限制，禁止登陆';
      case 23:
        return '试用期，超出在线总人数限制，禁止登陆，提示用户超出人数限制';
      case 24:
        return '注册期内剩余天数不足10天，提示用户续费，增加属性提示剩余天数';
      case 25:
        return '超出注册期，允许登陆，提示用户续费';
      case 26:
        return '注册期，超出数据库总人数限制，禁止登陆，提示用户超出人数限制';
      case 27:
        return '注册期，超出在线总人数限制，禁止登陆，提示用户超出人数限制';
      case 28:
        return '当前版本限制该设备登录';
      case 29:
        return '当前账号首次登录，需要短信验证码';
      case 30:
        return '短信验证码服务操作失败';
      case 31:
        return '验证码无效';
      case 32:
        return '验证码过期';
      case 33:
        return '获取验证码失败';
      case 201:
        return '参数错误';
      case 205:
        return '用户不存在';
      case 208:
        return '密码错误';
      case 220:
        return '命令无效';
      case 221:
        return '会话无效';
      case 223:
        return '用户账号在其它机器登录';
      case 225:
        return 'MAC地址不相符';
      case 260:
        return '用户设备号不相符';
      case 261:
        return '用户账号过期';
      case 262:
        return '域名不存在';
      case 263:
        return '用户密码输错次数超出或1分钟内登录次数超出，账号锁定';
      case 264:
        return '禁止移动端登录';
      case 265:
        return 'ldap验证服务有问题';
      case 266:
        return '异常IP登录';
      case 267:
        return '包含重复用户名';
      case 302:
        return '用户未登录';
      case 303:
        return '没有授权';
      case 304:
        return '用户已经存在';
      case 305:
        return 'WEB路径不存在';
      case 400:
        return '旧的密码不正确';
      case 402:
        return '远程服务不支持';
      case 404:
        return '文件不存在';
      case 407:
        return '服务不支持';
      case 501:
        return '数据库操作失败';
      case 502:
        return '创建消息文件失败';
      case 510:
        return '文件操作失败';
      case 521:
        return '第三方验证服务错误';
      case 540:
        return 'IM验证服务令牌错误';
      case 600:
        return '消息不存在';
      case 601:
        return '群组消息不存在';
      case 720:
        return '超出数量错误';
      case 912:
        return '无权限操作';
      case 928:
        return '群共享空间已满';
      case 929:
        return '操作超时';
      default:
        return '未知错误: $code';
    }
  }
}
